name: Terraform on AWS

# Controls when the workflow will run
on:  
  push:
    branches: [ main ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
          
      - name: Terraform FMT
        run: terraform fmt
        continue-on-error: true
      
      - name: Terraform Init
        run: terraform init -backend-config='bucket=${{ secrets.BUCKET_NAME }}'

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION : ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform plan -no-color
      
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION : ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform apply -auto-approve
        
  destroy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
          
      - name: Terraform Init
        run: terraform init -backend-config='bucket=${{ secrets.BUCKET_NAME }}'
        
      - name: Terraform Destroy
        run: terraform destroy
